name: build-actions

on:
  pull_request:
    branches: [ main ]
env: 
  NEXT_PUBLIC_TMDB_ACCESS_TOKEN: ${{env.NEXT_PUBLIC_TMDB_ACCESS_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install
      
      - name: build actions
        run: npm run build
        
      - run: npm run export
