name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setting token .env
        run: |
          echo "NEXT_PUBLIC_TMDB_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_TMDB_ACCESS_TOKEN }}" >> .env
          cat .env
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
        env: 
          NEXT_PUBLIC_TMDB_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_TMDB_ACCESS_TOKEN }}
